<script>
  export default {
    name: 'Footer'
  }
</script>

<template>
  <footer>
        <div class="container flex">

          <div class="society">
            <h3>Booleando s.r.l</h3>

            <ul class="foot-list">
              <li><a href="#">Inormazioni legali</a></li>
              <li><a href="#">Informativa sulla privacy</a></li>
              <li><a href="#">Diritto di recesso</a></li>
            </ul>
          </div>

          <div class="social">
            <span>Trovaci anche su</span>
          
            <ul class="foot-list">
                <li>
                  <a href="#"><i class="fa-brands fa-square-twitter"></i></a>
                </li>
            
                <li>
                  <a href="#"><i class="fa-brands fa-square-facebook"></i></a>
                </li>

                <li>
                  <a href="#"><i class="fa-brands fa-square-instagram"></i></a>
                </li>

                <li>
                  <a href="#"><i class="fa-brands fa-square-pinterest"></i></a>
                </li>

                <li>
                  <a href="#"><i class="fa-brands fa-square-youtube"></i></a>
                </li>
            </ul>
          </div>
        
        </div>
    </footer>
</template>