<script>
  export default {
    name: 'Main'
  }
</script>

<template>
  <main>
    <section class="container flex cards">

      <div class="product">

        <div class="trasp">
          <img class="model part" src="/img/1.webp" alt="relaxed tee">
          <img class="model view" src="/img/1b.webp" alt="relaxed tee">
          <span class="heart">&hearts;</span>
      
        
          <div class="label">
            <span class="sale">-50%</span>
            <span class="eco">Sostenibilità
            </span>
          </div>
        </div>

        <div class="info">
          <span class="brand">Levi's</span>
          <h3
          class="title">Relaxed fit tee unisex </h3>
          <span class="price-special">14,99&euro;</span>
          <span class="price">29,99 &euro;</span>
        </div>
        
      </div>

      <!-- guess -->

      <div class="product">

        <div class="trasp">
          <img class="model part" src="/img/2.webp" alt="relaxed tee">
          <img class="model view" src="/img/2b.webp" alt="relaxed tee">
          <span class="heart">&hearts;</span>
        </div>
        
        <div class="label">
          <span class="sale">-30%</span>
        </div>

        <div class="info">
          <span class="brand">Guess</span>
          <h3
          class="title">Roses tee </h3>
          <span class="price-special">20,99&euro;</span>
          <span class="price">29,99 &euro;</span>
        </div>
        
      </div>

      <!-- come zucchero filato -->

      <div class="product">

        <div class="trasp">
          <img class="model part" src="/img/3.webp" alt="relaxed tee">
          <img class="model view" src="/img/3b.webp" alt="relaxed tee">
          <span class="heart">&hearts;</span>
        </div>
        
        <div class="label">
          <span class="sale">-30%</span>
        </div>

        <div class="info">
          <span class="brand">Come Zucchero Filato</span>
          <h3
          class="title">voglia di colori pastello</h3>
          <span class="price-special">129,99&euro;</span>
          <span class="price">184,99 &euro;</span>
        </div>
        
      </div>

      <!-- levi's -->

      <div class="product">

        <div class="trasp">
          <img class="model part" src="/img/4.webp" alt="relaxed tee">
          <img class="model view" src="/img/4b.webp" alt="relaxed tee">
          <span class="heart">&hearts;</span>
        </div>
        
        <div class="label">
          <span class="sale">-50%</span>
          <span class="eco">Sostenibilità
          </span>
        </div>

        <div class="info">
          <span class="brand">Levi's</span>
          <h3
          class="title">tee unisex </h3>
          <span class="price-special">14,99&euro;</span>
          <span class="price">29,99 &euro;</span>
        </div>
        
      </div>

      <!-- maya deluxe -->

      <div class="product">

        <div class="trasp">
          <img class="model part" src="/img/5.webp" alt="relaxed tee">
          <img class="model view" src="/img/5b.webp" alt="relaxed tee">
          <span class="heart">&hearts;</span>
        </div> 

        <div class="info">
          <span class="brand">Maya Deluxe</span>
          <h3
          class="title">stripe bodice</h3>
          <span class="price-special">99,99&euro;</span>
        </div>
        
      </div>

      <!-- esprit -->

      <div class="product">

        <div class="trasp">
          <img class="model part" src="/img/6.webp" alt="relaxed tee">
          <img class="model view" src="/img/6b.webp" alt="relaxed tee">
          <span class="heart">&hearts;</span>
        </div>
        
        <div class="label">
          <span class="eco">Sostenibilità
          </span>
        </div>

        <div class="info">
          <span class="brand">Levi's</span>
          <h3
          class="title">Relaxed fit tee unisex </h3>
          <span class="price-special">29,99&euro;</span>

        </div>
        
      </div>

    </section>
  </main>

</template>

<style>

</style>

